# Generated by Django 5.2.5 on 2025-08-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
