# Generated by Django 5.2.5 on 2025-08-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0005_remove_post_imagen_alter_post_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
