# Generated by Django 5.2.5 on 2025-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0006_post_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
